name: Build 32-Bit Windows App

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build 32-Bit App
    runs-on: windows-latest 

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Yahan humne purana version (46.2.0) lagaya hai jo 32-bit support karta hai
      - name: Build App for 32-bit
        run: npx nativefier@46.2.0 --name "TodayVacancy" --platform "windows" --arch "ia32" "https://todayvacancy.in"

      - name: Upload 32-Bit .exe file
        uses: actions/upload-artifact@v4
        with:
          name: TodayVacancy-32Bit-App
          path: TodayVacancy-win32-ia32/